# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PG_USERNAME'] || 'postgres' %>
  password: <%= ENV['PG_PASSWORD'] || '' %>
  host: <%= ENV['PG_HOST'] || 'localhost' %>

development:
  <<: *default
  database: courses_api_development

test:
  <<: *default
  database: courses_api_test

production:
  <<: *default
  database: courses_api_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
